:spacer-1: {empty} + \

:spacer-2: {empty} + \
{empty} +

:spacer-3: {empty} + \
{empty} + \
{empty} +

:spacer-4: {empty} + \
{empty} + \
{empty} + \
{empty} +

:link-config-js: link:config.js[config.js]
:link-index-html: link:index.html[index.html]
:link-gitignore: link:.gitignore[.gitignore]
:link-db-json: link:db.json[db.json]
:link-bsconfig-json: link:bsconfig.json[bsconfig.json]
:link-c8-config-json: link:c8.config.json[c8.config.json]
:link-ava-config-js: link:ava/config.js[ava/config.js]
:link-scripts-dir: link:scripts[scripts/]
:link-src-dir: link:src[src/]
:link-package-json: link:package.json[package.json]
:link-tailwind-config-cjs: link:tailwind.config.cjs[tailwind.config.cjs]
:link-vite-config-js: link:vite.config.js[vite.config.js]

= starter-hybrids-tailwind

A setup for https://hybrids.js.org[hybrids], https://tailwindcss.com[tailwindcss] and https://rescript-lang.org/[Rescript].
{spacer-4}

== Installation

Where it https://pnpm.io[`pnpm`]s you can also `npm` or `yarn`. 
{spacer-3}

=== Using https://cli.github.com[gh]

Use this procedure if you want to create your own repo at the same time.

[source,bash]
----
gh repo create --template gourmetseasoningsake/starter-hybrids-tailwind --private my-project-name
----
[source,bash]
----
gh repo clone !$
----
[source,bash]
----
cd !$
----
[source,bash]
----
pnpm install
----
{spacer-1}

=== Using curl
This procedure simply downloads the files and folders from the main branch.

[source,bash]
----
mkdir my-project-name
----
[source,bash]
----
cd !$
----
[source,bash]
----
curl -L https://github.com/gourmetseasoningsake/starter-hybrids-tailwind/tarball/main | tar --strip=1 -x
----
[source,bash]
----
pnpm install
----
{spacer-2}

== Configuration
{spacer-1}

=== Define prefixes of exposed custom environment variables

In order to expose custom environment variables, they must have one of the prefixes specified in the `envPrefixes` array exported from {link-config-js}. The prefix `EXP_` is preconfigured and used in some files of the sample app.

If you plan to keep the sample app and want to change `EXP_` to something else, do a project-wide search to see where they are used.
{spacer-2}

=== Set exposed custom environment variables https://vitejs.dev/guide/env-and-mode.html#env-variables-and-modes[🔭] [[section-configuration-set-exp-vars]]

Besides the modes `development`, `production` used by vite, two other modes exist for the sample app: `staging` and `test`. The root folder contains .env.* files for each of these preconfigured modes with predefined effective variables. 

All env files contain all variables used by one or the other mode. Variables that are irrelevant to the particular mode are commented out. For example, see the link:.env.development[.env.development] file. Change the values, extend the variables with your own.
{spacer-2}

=== Set sensitive environment variables

Sensitive environment variables such as API-keys and passwords should be defined in .env files ending with `.local`. The provided {link-gitignore} file already ignores *.local files.
{spacer-2}

=== Templating the index.html file

You can template the {link-index-html} file with https://liquidjs.com/tutorials/intro-to-liquid.html[liquid] https://liquidjs.com/tags/overview.html[tags], outputs and https://liquidjs.com/filters/overview.html[filters]. The data passed to the template is located in link:config.js#L5-L24[config.js]. You can set a data item value in two ways, as primitive:

[source,javascript]
----
lang: "en"
----

or as object with properties per mode:

[source,javascript]
----
robots: {
  staging: "noindex,nofollow",
  production: "index,nofollow"
}
----

Accessing `{{ robots }}` in the template would render the value according the mode https://vitejs.dev/guide/env-and-mode.html#modes[Vite] is running in.
If no property matches the mode, the value is `null` and the https://liquidjs.com/tutorials/intro-to-liquid.html[liquid] template engine silently ignores it.

You can loop through object entries

[source,javascript]
----
og: {
  title: "...",
  type: "website",
  image: null,
  url: null,
  description: "Description",
  siteName: null,
}
----

in your index.html file,

[source,liquid]
----
{%- liquid 
  for item in og
    if item[1]
      echo '<meta property="og:%" content="%">' | subst: item[0], item[1]
    endif
  endfor 
-%}
----

where `item[0]` is the key and `item[1]` is the value.

NOTE: The `subst` filter is not standard liquidjs. It is a little extension defined in link:plugins/html.js#L25-L29[plugins/html.js].

{spacer-2}

== Usage

TODO

{spacer-2}

== References
{spacer-1}

=== Directory structure

[%header,cols="2,4,1"]
|===
|File / Directory
|Note
|Docs

|{link-ava-config-js}
|
|https://github.com/avajs/ava/blob/main/docs/06-configuration.md[🔭]

|{link-bsconfig-json}
|
|https://rescript-lang.org/docs/manual/latest/build-configuration[🔭]

|{link-c8-config-json}
|
|https://github.com/bcoe/c8#cli-options--configuration[🔭]

|The .env.* files
|
|<<section-configuration-set-exp-vars, 🔬>>

|{link-config-js}
|Some configurations specific to this starter project.
|

|{link-db-json}
|A data file to mimic a REST API used by the json-server package. Can be useful for development and testing. It contains sample data used for the sample app that can be completely removed, just like the app itself. If you do not plan to use fake API data, remove the json-server package and either adjust the scripts in the {link-package-json} file or the scripts in {link-scripts-dir}.
|https://github.com/typicode/json-server#getting-started[🔭]

|{link-index-html}
|The entry point to the app with references to source files in {link-src-dir}.
|https://vitejs.dev/guide/#index-html-and-project-root[🔭]

|{link-scripts-dir}
|Script files used in the {link-package-json} file.
|

|{link-src-dir}
|The source files. It contains a sample app that can be deleted completely.
|

|{link-tailwind-config-cjs}
|
|https://tailwindcss.com/docs/configuration[🔭]

|{link-vite-config-js}
|
|https://vitejs.dev/config/[🔭]

|===



