:spacer-1: {empty} + \

:spacer-2: {empty} + \
{empty} +

:spacer-3: {empty} + \
{empty} + \
{empty} +

:spacer-4: {empty} + \
{empty} + \
{empty} + \
{empty} +

= starter-hybrids-tailwind

A setup for https://hybrids.js.org[hybrids], https://tailwindcss.com[tailwindcss] and https://rescript-lang.org/[Rescript].
{spacer-4}

== Installation

Where it https://pnpm.io[`pnpm`]s you can also `npm` or `yarn`. 
{spacer-3}

=== Using https://cli.github.com[gh]

Use this procedure if you want to create your own repo at the same time.

[source,bash]
----
gh repo create --template gourmetseasoningsake/starter-hybrids-tailwind --private my-project-name
gh repo clone !$
cd !$
pnpm install
----
{spacer-1}

=== Using curl
This procedure simply downloads the files and folders from the main branch.

[source,bash]
----
mkdir my-project-name
cd !$
curl -L https://github.com/gourmetseasoningsake/starter-hybrids-tailwind/tarball/main | tar --strip=1 -x
pnpm install
----
{spacer-2}

== Configuration
{spacer-1}

=== Define prefixes of custom environment variables

In order to expose custom environment variables, they must have one of the prefixes specified in the `envPrefixes` array exported from link:config.js[config.js]. The prefix `EXP_` is preconfigured.
{spacer-2}

=== List the modes

The modes directly correspond to the suffix of the env files, `.env.[this part]`. For now, you need to list the modes in the `modes` array exported from link:config.js[config.js]. This will change soon and won't be necessary anymore.
{spacer-2}

=== Set custom environment variables

The root folder contains sample.env.* files for common environments with predefined effective variables using the preconfigured prefix `EXP_`. Change or extend the variables and finally remove the "sample" part of the filename to reveal them to https://vitejs.dev/guide/env-and-mode.html#env-variables-and-modes[Vite].

All env files contain all variables used by one or the other mode. Commented variables basically mean that they are irrelevant for the corresponding mode. See for example the link:sample.env.development[sample.env.development] file:

[source,bash]
----
EXP_BROWSER=google chrome
EXP_HMR_FORCE_RELOAD=
EXP_ASS_DISABLE=
EXP_ROUTER_DEBUG=true
#EXP_BUILD_MINIFY=
#EXP_TEST_VERBOSE=
EXP_DB_PATH=db.json
EXP_API_PROTOCOL=http
EXP_API_HOST=localhost
EXP_API_PORT=3001
EXP_API_PATH=

# derived
EXP_API_URL=$EXP_API_PROTOCOL://$EXP_API_HOST:$EXP_API_PORT$EXP_API_PATH

# behavior
NODE_ENV=development
----


