:spacer-1: {empty} + \

:spacer-2: {empty} + \
{empty} +

:spacer-3: {empty} + \
{empty} + \
{empty} +

:spacer-4: {empty} + \
{empty} + \
{empty} + \
{empty} +

= starter-hybrids-tailwind

A setup for https://hybrids.js.org[hybrids], https://tailwindcss.com[tailwindcss] and https://rescript-lang.org/[Rescript].
{spacer-4}

== Installation

Where it https://pnpm.io[`pnpm`]s you can also `npm` or `yarn`. 
{spacer-3}

=== Using https://cli.github.com[gh]

Use this procedure if you want to create your own repo at the same time.

[source,bash]
----
gh repo create --template gourmetseasoningsake/starter-hybrids-tailwind --private my-project-name
gh repo clone !$
cd !$
pnpm install
----
{spacer-1}

=== Using curl
This procedure simply downloads the files and folders from the main branch.

[source,bash]
----
mkdir my-project-name
cd !$
curl -L https://github.com/gourmetseasoningsake/starter-hybrids-tailwind/tarball/main | tar --strip=1 -x
pnpm install
----
{spacer-2}

== Directory structure

The most important files and folders:

* link:index.html[index.html] The entry point to your application with references to source files. https://vitejs.dev/guide/#index-html-and-project-root[&#8505;]
* link:src[src/] The source files of an example application. You can completely replace the entire folder with your own. Just adjust the references in your index.html, e.g. ```<script src="/a/file.js">```.
* ...

{spacer-2}

== Start

If the installation went successful, you should be able to start working.

=== Development

[source,bash]
----
pnpm dev
----

This command starts the https://vitejs.dev/guide/env-and-mode.html#env-variables-and-modes[Vite] dev server

== Configuration
{spacer-1}

=== Define prefixes of custom environment variables

In order to expose custom environment variables, they must have one of the prefixes specified in the `envPrefixes` array exported from link:config.js[config.js]. The prefix `EXP_` is preconfigured.
{spacer-2}

=== List the modes

The modes directly correspond to the suffix of the env files, `.env.[this part]`. For now, you need to list the modes in the `modes` array exported from link:config.js[config.js]. This will soon change and won't be necessary anymore. The modes `development`, `production`, `staging` and `test` are preconfigured.
{spacer-2}

=== Set custom environment variables

The root folder contains sample.env.* files for the preconfigured modes with predefined effective variables. 

All env files contain all variables used by one or the other mode. Variables irrelevant for the corresponding mode are commented-out. See For example the link:sample.env.development[sample.env.development] file.

Change the values, extend the variables with your own and finally remove the "sample" part of the filename to reveal them to https://vitejs.dev/guide/env-and-mode.html#env-variables-and-modes[Vite].
{spacer-2}


